apiVersion: v1
kind: ConfigMap
metadata:
  name: #{configmap}#
  namespace: #{namespace}#
data:
  application.yaml: |-
    server:
      port: 8080
      servlet:
        context-path: /api/v1
    spring:
      CustomerDebt:
        name: customer-debts
      jpa:
        show-sql: true
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
          ddl-auto: validate
      datasource:
        url: jdbc:postgresql://#{postgres-host}:#{postgres-port}/#{postgres-dbname}
        username: #{postgres-username}
        password: #{postgres-password}
        driverClassName: org.postgresql.Driver
      cache:
        type: redis
      redis:
        host: #{redis-host}
        port: #{redis-port}
      messages:
        basename: i18n/messages
        encoding: UTF-8
        fallback-to-system-locale: false
    jwt:
      secret:
        key: #{jwt-secret-key}
